import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import AdminLayout from "./layout/MainLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
      >
        <ThemeProvider attribute="class" defaultTheme="dark">

          <AdminLayout>

            {children}
          </AdminLayout>

        </ThemeProvider>

      </body>
    </html>
  );
}
